name: cnn_gpu

channels:
    - conda-forge
    - pnlbwh
    
dependencies:
    - python==3.6
    - tensorflow-gpu==1.12.0
    - cudatoolkit==9.0
    - cudnn==7.6.0
    - keras==2.2.4
    - numpy==1.16.4
    - nibabel==2.2.1
    - scikit-image==0.16.2
    - ants
    - pip
    - pip:
        - gputil
        - git+https://github.com/pnlbwh/conversion.git
        
 # source python36/bin/activate   
 # conda env create --file=environment.yml
 # conda activate cnn_gpu_senthil
 # To have conda, you first need to install python 3.6, conda comes with python
